files:
  ignore:
    - "node_modules/**/*.s+(a|c)ss"
rules:
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
  indentation:
    - 1
    - size: "tab"
  no-color-literals:
    - 0
  no-misspelled-properties:
      - 1
      - extra-properties:
          - composes